name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # checkout repository
      - uses: actions/checkout@v4

      # install just
      - uses: extractions/setup-just@v3
      
      # install pnpm (using cache)
      # (see https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time)
      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          version: 10
          run_install: false

      # setup .npmrc file to publish to GitHub Packages
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@benrbray'

      # install dependencies
      - name: Install Dependencies
        run: pnpm install

      # build package
      - name: Build Package
        run: |
          just build
          mkdir -p release

      # publish to package registry
      - name: Publish to GitHub Package Registry
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # create tarball for release
      - name: Create Tarball
        run: |
          pnpm pack --out release/mathviz.tgz

      # create release, upload artifact
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/mathviz.tgz"
          artifactContentType: application/gzip
